### ISSUE TITLE
和setu_now插件好像互相冲突，可以修一下吗

### ISSUE THREAD

**Issue by wu5288540** [Special-Week/nonebot_plugin_smart_reply#2]
如题，报错的是setu_now那边，不知道是哪里冲突了 [笑哭]

**Comment by Special-Week** [comment]
具体是什么报错呢

**Comment by wu5288540** [comment]
奇怪，你刚回复我，我重启插件后倒是正常工作了，但用了一会又开始抽风，时灵时不灵。接收到指令后，后台有了反应，但是产生了关于matcher的报错，不是必定出现，有点玄学，禁用自动回复可以彻底解决。我贴一下报错代码给你吧

06-27 17:06:05 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.10/site-packages/nonebot_plugin_setu_now/__init__.py", line 99, in _
    data = await setu_obj.get_setu(key, tags, r18, num)
  File "/usr/local/lib/python3.10/site-packages/nonebot_plugin_setu_now/data_source.py", line 66, in get_setu
    api_data = await self._get_info_from_setu_api(keyword, tags, r18, num)
  File "/usr/local/lib/python3.10/site-packages/nonebot_plugin_setu_now/data_source.py", line 110, in _get_info_from_setu_api
    data = res.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wu5288540** [comment]
好像也有其他插件被传染了，复读机突然报了liset index out of range，也是偶发，怪
我自己也再看看吧，不知道是不是我这边系统的问题_(:3」∠)_

**Comment by wu5288540** [comment]
好吧，我的插件连环报错了，得重启机器了[笑哭]
